export const Data = [
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 95,
    country: "Nigeria",
    flag: "/activity.png",
    location: "Iwo road, Ibadan",
  },
  {
    Id: "2",
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    country: "Nigeria",
    flag: "/activity.png",
    progress: 99,
    location: "Iwo road, Ibadan",
  },
  {
    Id: "3",
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 75,
    location: "Iwo road, Ibadan",
    country: "Nigeria",
    flag: "/activity.png",
  },
  {
    Id: "4",
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 51,
    location: "Iwo road, Ibadan",
    country: "Nigeria",
    flag: "/activity.png",
  },
  {
    Id: "5",
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 80,
    location: "Iwo road, Ibadan",
    country: "Nigeria",
    flag: "/activity.png",
  },
  {
    Id: "6",
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 95,
    location: "Iwo road, Ibadan",
    country: "Nigeria",
    flag: "/activity.png",
  },
  {
    Id: "7",
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 45,
    location: "Iwo road, Ibadan",
    country: "Nigeria",
    flag: "/activity.png",
  },
  {
    Id: "8",
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 65,
    location: "Iwo road, Ibadan",
    country: "Nigeria",
    flag: "/activity.png",
  },
  {
    Id: "9",
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 52,
    location: "Iwo road, Ibadan",
    country: "Nigeria",
    flag: "/activity.png",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 52,
    location: "Iwo road, Ibadan",
    country: "Nigeria",
    flag: "/activity.png",
  },
];
