export const Data = [
  {
    name: "Temms Tayo",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 60,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 95,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 99,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 75,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 51,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 80,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 95,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 45,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 65,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 52,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 52,
    location: "Iwo road, Ibadan",
  },
];
