export const Data = [
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 20,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 45,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 99,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 87,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 22,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 78,
    location: "Iwo road, Ibadan",
  },
];
