// export const Data = [];
// export const FarmersList = [];
export const FarmersList = [
  {
    name: "Jaja Prosper",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Mentor Dami",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Blessing Okeoma",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Jaja Prosper",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Ify Hafsah",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: false,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
  {
    name: "Agent White",
    id: "AM131242",
    phone: "08192832838",
    email: "jpropser@email.com",
    assigned: "Temitayo Olawale",
    address: "kaduna, Kaduna",
    country: "nigeria",
    mapped: true,
  },
];
export const Data = [
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 95,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 99,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 75,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 51,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 80,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 95,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 45,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 65,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 52,
    location: "Iwo road, Ibadan",
  },
  {
    name: "Adesola Saga",
    phone: "08018634652",
    email: "saga@gmail.com",
    farmers: "Tayo Aina",
    mapped: "123,455",
    progress: 52,
    location: "Iwo road, Ibadan",
  },
];
